version: '3.9'
services:
  # backend:
  #   build: .
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db

  db:
    platform: linux/arm64/v8
    image: arm64v8/mysql:oracle
    restart: always
    environment:
      MYSQL_DATABASE: meet_appointment
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
